name: Github Page Deploy Workflow

on:
  push:
    branches: [main]

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
    
      - name: Setup Environment
        run: npm ci

      - name: Build
        run: npm run build

      - name: Upload Artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: build/

      - name: Deploy to Glavonnet
        uses: easingthemes/ssh-deploy@main
        with:
          SSH_PRIVATE_KEY: ${{ secrets.GLAVON_SSH_KEY }}
          ARGS: "-rlgoDzvc -i"
          SOURCE: "dist/"
          REMOTE_HOST: ${{ secrets.GLAVON_DEPLOY_HOST }}
          REMOTE_USER: ${{ secrets.GLAVON_DEPLOY_USER }}
          TARGET: ${{ secrets.GLAVON_DEPLOY_TARGET }}
          EXCLUDE: "/dist/, /node_modules/"
          SCRIPT_BEFORE: |
            whoami
            ls -al
          SCRIPT_AFTER: |
            whoami
            ls -al
            echo $RSYNC_STDOUT

  # deploy-gh-pages:
  #   needs: setup
  #   runs-on: ubuntu-latest
  #   permissions:
  #     pages: write
  #     id-token: write
  #   environment:
  #     name: main-deploy
  #     url: ${{ steps.deployment.outputs.page_url }}
  #   steps:
  #     - name: Deploy to Github Pages
  #       id: deployment
  #       uses: actions/deploy-pages@v2